### ISSUE TITLE
Idea: PatchMaster remote patch points

### ISSUE THREAD

**Issue by kamidon** [MarcBoule/MindMeldModular#103]
First, thank you for PatchMaster. I have wanted something like it since starting to play with VCV-Rack and your implementation of the idea is awesome.

When playing around with trying to emulate synthesizers in VCV-Rack, for semi-modulars I think it would complete the functionality to be able to add labeled patch points in PatchMaster.

For an output patch point in PatchMaster I imagine you could just map an existing output patch point in the main patch which would also appear on the patch point in PatchMaster.

For an input patch point in PatchMaster I imagine you could map the patch point to a "normaled remote patch" module somewhat similar in spirit to the RouteMaster modules which would provide some number of patch points each with one input and one output. If nothing is patched into the patch point in PatchMaster, the output would reflect whatever was on the input point (or nothing if it isn't patched). If a cable is inserted into the patch point in PatchMaster, that connection would be virtually "broken" and the output would come from the whatever was patched into the PatchMaster point.

Thanks for considering this idea!

**Comment by MarcBoule** [comment]
Hi, many people have suggested something in the lines of a patchbay (with labels and in/out ports), to help with organizing a patch and such, so we are considering something in those lines. I think your request is perhaps a little different, unless I'm miunderstanding it, but since PatchMaster has no inputs and outputs (and never will), it will have to be a separate module.

**Comment by kamidon** [comment]
I suspect a separate patchbay module as you're imaging would meet my requirements as well and will be happy to wait to see how that develops given you'd prefer not to have inputs and outputs in PatchMaster itself. For what it is worth, I'm not sure if there is a technical reason not to have inputs and outputs in PatchMaster itself, but the one nice aspect of doing that is that you could create functional groupings with the user controls like switches, knobs, etc. grouped with the relevant patch points. In any case. Thanks for all the great modules you've created. I'm a happy user of MixMaster Pro, ShapeMaster Pro, and all your other modules.

**Comment by kamidon** [comment]
Thinking a bit more, one aspect of my idea that might not be captured by the patch bay concept or that might be incorporated in it is making it easy for "plugging a cable" a cable in to a port in the patchbay to break a "normaled" connection elsewhere in the patch.

**Comment by kamidon** [comment]
Thanks for the insight into what you're planning. I'll look forward to trying out the patchbay when it's ready.
