### ISSUE TITLE
VCV Rack 2.3.0 SDK change has impaired Patch Master remote parameter control.

### ISSUE THREAD

**Issue by DaveBenham** [MarcBoule/MindMeldModular#106]
I believe the 2.3.0 SDK change to ParamQuantity::set/getValue() has made the Patch Master remote parameter control unreliable, as it now uses what used to be called set/getSmoothValue(). I suspect you are using set/getValue(), and you now need to use set/getImmediateValue().

For example, I have a knob that is supposed to map from -5 to +5 volts. But since I upgraded to Rack 2.3.0 the knob extreme values are between -4.9x and 4.9x, where x varies.

**Comment by DaveBenham** [comment]
I believe the 2.3.0 SDK change to ParamQuantity::set/getValue() has made the Patch Master remote parameter control unreliable, as it now uses what used to be called set/getSmoothValue(). I suspect you are using set/getValue(), and you now need to use set/getImmediateValue().

For example, I have a knob that is supposed to map from -5 to +5 volts. But since I upgraded to Rack 2.3.0 the knob extreme values are between -4.9x and 4.9x, where x varies.

**Comment by MarcBoule** [comment]
Fixed and updated in the library
