### ISSUE TITLE
Shapemaster Pro; different note length; how to trigger?

### ISSUE THREAD

**Issue by poulpoulsen** [MarcBoule/MindMeldModular#107]
Hello, i am using your pro Version since some Werks and the usage is more than satisfied.
Currently i will use Shapemaster for sequencing. Therefore it is common to input notes with different durations, 1/4 1/8 and so on.
I am struggling to use notes with Intervalls between them, e.g. 1/4 note, 1/8 Intervall, 1/8 note.
As far as i see, the shape for the Intervall is 0volt and therefore interpreted as a c note.
This will be not correct, because it has to be empty space.
Is there any way to tell the shape or especially the grid to insert an Intervall?
Hope it is clear what i mean.
Cheers,
Jens

**Comment by MarcBoule** [comment]
Hi, I'm not sure I understand the request. In the first part of your message you are mentioning not durations (horizontal axis in ShapeMaster), and then mentioning that 0V is a C note (vertical axis in ShapeMaster). There is no way to have an "empty" voltage in modular synthesis, a voltage must always be present. For intervals, you have to make them using the nodes and shape exactly what you want. Apologies if I misunderstood your question.

**Comment by poulpoulsen** [comment]
Hello, thanks for the quick answer. I will explain it a bit deeper.
The horizontal axis means time, right? Therefore a 1/8 note is half shorter than a 1/4 note, right?
The vertical axis means note pitch. Therefore 0volts means "c4" note.
If i want to play a 1/4 note "e" then a Pause and then a 1/8 note "g" for example, the Pause is filled with 0volt. Shapemaster will output it as CV. But it should be a Pause, means no note.
How could i insert these kind of Melodie?

**Comment by Petervos2018** [comment]
I think I know what you want, you want “Note Off”. so there is no sound. The only way you can do that is by NOT sending a gate to the VCA, All VCOs are ALWAYS outputting sound, the only way we can NOT hear them is by not opening the gate (same with all keyboards, as long as you don’t play a note on the keyboard you hear no sound).

It does not matter what note ( 0V or 1V) is played by the OSC as long as the gate is closed you won’t hear it.

So for a rest in your SEQ you need to NOT have a GATE. (gate=0).

**Comment by MarcBoule** [comment]
Thank you @Petervos2018 for the follow up, this is exactly it. We can't have the absence of a pitch voltage, this is logically impossible, and so when we want no note, we must turn off the gate to a VCA-EG pair. In this specific case, you would need to use another channel in ShapeMaster for creating a gate signal. This might be too messy for your tastes, but that is where timeline sequencers come into play, and where some of the Entrian sequencers in Rack might be more apropriate for this use case. I hope both of these answerers help to clear things up. Cheers!
