### ISSUE TITLE
MixMaster feature request

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#108]
In the channel context menu could we have a copy track menu settings to all option please?

**Comment by MarcBoule** [comment]
sorry, that's a bit to narrow of a use case to warrant adding more to our menus unfortunately

**Comment by Petervos2018** [comment]
> In the channel context menu could we have a copy track menu settings to all option please?

When you hold down ctrl (on PC) the menu won't close and you can copy it to all tracks pretty fast 😃

**Comment by MarcBoule** [comment]
indeed, nice trick, I had forgotten about that :-)
