### ISSUE TITLE
Mappings not preserved in Patchmaster module

### ISSUE THREAD

**Issue by PondRacer1** [MarcBoule/MindMeldModular#109]
Controller mappings are not preserved/saved within Patchmaster when you close VCV, then open it back up, or when you save as part of a selection, and I have to map the different parameters every time.

**Comment by Petervos2018** [comment]
`or when you save as part of a selection`

https://github.com/MarcBoule/MindMeldModular#preserving-mappings-in-saved-selections

**Comment by Torinbob** [comment]
Hi Pondracer1,

Controller mappings are preserved fine my end when closing VCV and opening it again. What OS/Architecture/Rack version etc are you on? I think we would be hearing a lot more about this if it was a common problem...

Regarding saving as a selection and importing, this is an issue with Rack itself which ignores mappings in imported selections. As Peter Cos pointed out in our manual, Stoermelder has a module called S++ which can be used to import selections with the mapping intact (they can be saved from Rack as normal).

**Comment by flarn2006** [comment]
Can someone please link to the S++ module? I'm not seeing it in the library.

**Comment by MarcBoule** [comment]
This module was renamed by its author to Strip++ and our readme had not been updated unfortunately. We have updated our readme just now, and added links, so it should now be easy to find. Sorry for the confusion! :-)

**Comment by flarn2006** [comment]
Thank you!

**Comment by flarn2006** [comment]
Looks like you accidentally renamed the readme file as well.

**Comment by MarcBoule** [comment]
Oh my! Thanks for mentioning it!!
