### ISSUE TITLE
PatchMaster Vertical Separator is crashing ARM64 Rack v 2.4.1 on macOS 14

### ISSUE THREAD

**Issue by pgatt** [MarcBoule/MindMeldModular#110]
```
[39.623 info src/app/Browser.cpp:201 createPreview] Creating module widget MindMeld PatchMaster Vertical Separator
[40.561 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 15. Stack trace:
25: Rack(fatalSignalHandler(int)+40)
24: libsystem_platform.dylib(_sigtramp+56)
23: libsystem_c.dylib(__sread+24)
22: libsystem_c.dylib(_sread+32)
21: libsystem_c.dylib(__srefill1+36)
20: libsystem_c.dylib(_fseeko+732)
19: libsystem_c.dylib(fseek+92)
18: libRack.dylib(nsvgParseFromFile+60)
17: libRack.dylib(rack::window::Svg::loadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)+72)
16: libRack.dylib(rack::window::Svg::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)+156)
15: plugin.dylib(PatchMasterBlankWidget::PatchMasterBlankWidget(PatchMasterBlank*)+168)
14: plugin.dylib(rack::plugin::Model* rack::createModel<PatchMasterBlank, PatchMasterBlankWidget>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>)::TModel::createModuleWidget(rack::engine::Module*)+100)
13: libRack.dylib(rack::app::browser::ModelBox::createPreview()+460)
12: libRack.dylib(rack::app::browser::ModelBox::draw(rack::widget::Widget::DrawArgs const&)+36)
11: libRack.dylib(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+136)
10: libRack.dylib(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+136)
9: libRack.dylib(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+136)
8: libRack.dylib(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+136)
7: libRack.dylib(rack::ui::ScrollWidget::draw(rack::widget::Widget::DrawArgs const&)+48)
6: libRack.dylib(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+136)
5: libRack.dylib(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+136)
4: libRack.dylib(rack::widget::Widget::draw(rack::widget::Widget::DrawArgs const&)+136)
3: libRack.dylib(rack::window::Window::step()+1728)
2: libRack.dylib(rack::window::Window::run()+40)
1: Rack(main+3428)
0: dyld(start+2224)
```

Not sure if other OSes are affected, can't reproduce on x64 Mac here.

**Comment by MarcBoule** [comment]
Just to be sure, are you compiling the lastest version from source code on github, or is this the library version?

**Comment by pgatt** [comment]
Not sure, wasn't my log but a user who contacted support. Their log says 2.2.3, but I will check for you.

**Comment by MarcBoule** [comment]
I tried again on my Windows machine and I couldn't get it to crash after about 50 open/close cycles with a patch containing about 30 PM Blank modules. Those two crashes I reported above were perhaps not related (could be rtAudio glitches, or I did something stupid). 

In any case, I see from the log that it's crashing when my `PatchMasterBlankWidget` constructor is calling a Rack function with a simple file name, i.e. here:

```APP->window->loadSvg(asset::plugin(pluginInstance, "res/dark/patchset/pm-vsep-bg.svg"))```

so I'm not sure how to debug this more. If I give it a bad filename it should just not load the svg, it should definitely not crash. So this looks like it's Rack related to me. PatchMaster has been out for a while now and I've not gotten any specific bug report in any way similar to what you showed above, so I'm not sure the issue is with my code. But as always, I try to keep an open mind on these things, and I will try my M1 over the weekend. In the mean time, do you have the user's patch? It would definitely help since right now I have no other leads to follow.

**Comment by pgatt** [comment]
Following up with the user and waiting for more detail but they have noted that Rack crashed when opening the module browser if I've understood correctly.

**Comment by MarcBoule** [comment]
I tried in a patch and in the module browser on ARM64 M1 and can't reproduce the crash

**Comment by pgatt** [comment]
User was on the Library version.

**Comment by pgatt** [comment]
There's possibly a little more detail, the PatchMaster vertical separator was in their patch, but their description of the crash is that Rack crashed when opening the module browser.

**Comment by MarcBoule** [comment]
That's good to know, but I'm still unsure as to how my module can be crashing Rack. That module has almost no code in it and I really don't know where to look. Can the user reproduce the crash every time? I suspect that another module may be misbehaving (developers sometimes tend to forget to check for a null module pointer in their ModuleWidgets...), and if that module is writing garbage in memory, then it may make it look as though another module/plugin is the culprit. The cue for me that it's likely not my code, is that the crash log shows it crashing in Rack methods in lines 16 and 17, after I call an SVG load in my code (which is extremely simple). Both those code locations (the Rack code and my constructor) are so basic and is so fundamental to the way all modules work, that I doubt there is a bug with Rack or PatchMasterBlank. If ever the user can repeat the bug consistently, I would wager that as they remove plugins one by one from their plugins folder to a temp folder, that at one point they will not get the crash, and the plugin last moved will likely indicate the culprit.

**Comment by pgatt** [comment]
Fair enough, I reckon you close this and we revisit if it comes up again.On 31 Oct 2023, at 12:37 am, Marc Boulé ***@***.***> wrote:﻿
That's good to know, but I'm still unsure as to how my module can be crashing Rack. That module has almost no code in it and I really don't know where to look. Can the user reproduce the crash every time? I suspect that another module may be misbehaving (developers sometimes tend to forget to check for a null module pointer in their ModuleWidgets...), and if that module is writing garbage in memory, then it may make it look as though another module/plugin is the culprit. The cue for me that it's likely not my code, is that the crash log shows it crashing in Rack methods in lines 16 and 17, after I call an SVG load in my code (which is extremely simple). Both those code locations (the Rack code and my constructor) are so basic and is so fundamental to the way all modules work, that I doubt there is a bug with Rack or PatchMasterBlank. If ever the user can repeat the bug consistently, I would wager that as they remove plugins one by one from their plugins folder to a temp folder, that at one point they will not get the crash, and the plugin last moved will likely indicate the culprit.

**Comment by MarcBoule** [comment]
all good
