### ISSUE TITLE
Please correct the manual V1_1_4 (p. 15 / chapters "GROUP BUS MENU" and "MASTER BUS MENU"

### ISSUE THREAD

**Issue by BMuXBeats** [MarcBoule/MindMeldModular#112]
The menues in MIXMASTER Jr an MIXMASTER differ from the pics in the manual.

![](https://github.com/MarcBoule/MindMeldModular/assets/102815175/3f3f583a-3e68-4e87-bc99-34b6cf111f17)

![](https://github.com/MarcBoule/MindMeldModular/assets/102815175/49cf0aae-4c4d-43fa-8e7a-f7a1414abbe8)

Some of the settings, mentioned in the manual, aren't present (s. pics above).

**Comment by MarcBoule** [comment]
[see answer in issue #111]
