### ISSUE TITLE
Light Mode Not Working?

### ISSUE THREAD

**Issue by limitedAtonement** [MarcBoule/MindMeldModular#113]
I'm using cardinal 24.05. When I turn dark mode on and off, the mind meld plugins don't change:

![image](https://github.com/user-attachments/assets/ede0f04c-f042-4934-9d06-903b2a15fc53)

**Comment by MarcBoule** [comment]
Hi, Unfortunately MindMeld modules do have light skins, and thus there is no light skin to change to when that option is toggled. This is a design decision with the MindMeld modules, as we did not want to offer the modules in a light tone, and thus the behavior observed is not a bug with Cardinal. The same happens in VCV Rack also.
