### ISSUE TITLE
Tab over to name several tracks?

### ISSUE THREAD

**Issue by jeremywen** [MarcBoule/MindMeldModular#12]
This is a minor request.  I just connected a bunch of voices and now I want to name them.  Would it be possible to allow the tab key to focus and select the track on the right so I can quickly rename the tracks?

**Comment by MarcBoule** [comment]
Hi Jeremy, thanks, I'll look into it and see what I can do.

**Comment by MarcBoule** [comment]
Done. Will be in the next version of the plugin. Thanks for the suggestion JW!
