### ISSUE TITLE
Fade toggle

### ISSUE THREAD

**Issue by EmergencyPeanut** [MarcBoule/MindMeldModular#13]
Hi,

Maybe I'm missing something here. I am trying to trigger fades using a sequencer but as both on and off use a rising edge I do not seem to be able to sync the state of the mixer to the position in the sequence.

If this is not currently possible could a gate mode be added so a trailing edge would swtch off a fade?

cheers for a great mixer

**Comment by MarcBoule** [comment]
Hi EP, this has been added in our development version, and will be in the next release of the plugin. If ever you want to test it before it gets submitted to the plugin manager, we should be posting some preview builds quite soon in the releases section of our github. Thanks!

**Comment by EmergencyPeanut** [comment]
Thanks Maec. Sounds great, look forward to it
