### ISSUE TITLE
MixMaster 1.1.2 Aux send config does not take -10, sets to +10

### ISSUE THREAD

**Issue by fractalgee** [MarcBoule/MindMeldModular#14]
I just found a very odd bug: (Mac, Rack 1.1.6, MindMelt 1.1.2, released version)

In the mixmaster auxspander I have one row being delay (row 2) send. I have them set via right click to -15dB. so far so good. Now I right click and try to set it to -10 and it jumps top +10, while tool tip insists it is -10, but it's on 10, but if I turn left it goes to 0 and then to -10 left of center again where -10 should be. right click to set to same -10 it is set to? back to +10 it jumps while tool tip says -10 still (again?)  ;)

No exhaustive checking done to see what other numbers have this issue where - gets ignored by what it seems, or if it affects all rows used...

**Comment by Torinbob** [comment]
Thanks for reporting this. I can repeat the issue. We will investigate and keep you posted.

**Comment by fractalgee** [comment]
Excellent, glad it's easily reproducible there too.

One more note, -15/-20/-25/-30/-35/-40/... all the way to -55 take fine,
just -10 (and possibly closer to 0 ) has this issue, so I am very curious
what might cause something like this :)
