### ISSUE TITLE
Feature request: Editable title in Meld/Unmeld

### ISSUE THREAD

**Issue by spectromas** [MarcBoule/MindMeldModular#15]
It would be quite cool if you could label these modules according to what they are doing. Not sure if it's possible but making the Meld/Unmeld text editable so it can instead be a custom label would be perfect.

**Comment by ContemporaryInsanity** [comment]
More modules could use this imo.  See ScribbleStrip in my RSComponents.hpp, intended to look like any other label, used in Boogie Bay H8.  Perfectly usable as is but a work in progress.

**Comment by MarcBoule** [comment]
Hi Guys,
I spoke with Steve and it doesn't appear we will make the module names editable. To help differentiate them in their functions though, they do have selectable panels in their right-click menus for Tracks 1-8, Tracks 9-16 and Group/Aux connections. Hope this can help.
Cheers,
Marc
