### ISSUE TITLE
Lab branch compile error [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [MarcBoule/MindMeldModular#16]
g++  -std=c++11 -Wsuggest-override   -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/MindMeldModular.cpp.o src/MindMeldModular.cpp
In file included from src/EqMasterCommon.hpp:13,
                 from src/EqMenus.hpp:13,
                 from src/EqWidgets.hpp:12,
                 from src/EqMaster.cpp:9:
src/dsp/QuattroBiQuad.hpp: In member function 'rack::simd::float_4 QuattroBiQuadCoeff::getFrequencyResponse(float)':
src/dsp/QuattroBiQuad.hpp:129:30: error: 'hypot' is not a member of 'rack::simd'
  129 |   simd::float_4 norm = simd::hypot(num[0] / denom,  num[1] / denom);
      |                              ^~~~~
src/dsp/QuattroBiQuad.hpp:129:30: note: suggested alternatives:
In file included from C:/msys64/mingw64/include/c++/9.2.0/cmath:45,
                 from ../../include/common.hpp:10,
                 from ../../include/rack.hpp:6,
                 from src/MindMeldModular.hpp:12,
                 from src/EqMasterCommon.hpp:12,
                 from src/EqMenus.hpp:13,
                 from src/EqWidgets.hpp:12,
                 from src/EqMaster.cpp:9:
C:/msys64/mingw64/x86_64-w64-mingw32/include/math.h:876:25: note:   'hypot'
  876 |   extern double __cdecl hypot (double, double) __MINGW_ATTRIB_DEPRECATED_MSVC2005; /* in libmoldname.a */
      |                         ^~~~~
In file included from ../../include/common.hpp:10,
                 from ../../include/rack.hpp:6,
                 from src/MindMeldModular.hpp:12,
                 from src/EqMasterCommon.hpp:12,
                 from src/EqMenus.hpp:13,
                 from src/EqWidgets.hpp:12,
                 from src/EqMaster.cpp:9:
C:/msys64/mingw64/include/c++/9.2.0/cmath:1469:5: note:   'std::hypot'
 1469 |     hypot(_Tp __x, _Up __y)
      |     ^~~~~
make: *** [../../compile.mk:69: build/src/EqMaster.cpp.o] Error 1

**Comment by MarcBoule** [comment]
Hi Steve,

That's weird, since it builds fine on my Win10. Are you sure you are using the latest Rack sources?
This line in your error log

`src/dsp/QuattroBiQuad.hpp:129:30: error: 'hypot' is not a member of 'rack::simd'`

leaves me to belive your Rack sources may not be up to date, since `hypot()` is part of `rack::simd` as can be seen [here](https://github.com/VCVRack/Rack/blob/v1/include/simd/functions.hpp#L173).

**Comment by SteveRussell33** [comment]
Hi Marc,

You were right. I've been working on a separate fork and hadn't updated Rack dev source for about a month.

Cheers.
