### ISSUE TITLE
Request: add stereo width control

### ISSUE THREAD

**Issue by johnnovak** [MarcBoule/MindMeldModular#17]
It would be very useful to add stereo width control in addition to the pan control for stereo channels (when both the L and R inputs are in use). I understand this would complicate the UI and everything, but it's a really useful feature to have. This is one of the few missing things to make this mixer truly great :) You can check it out how the stereo balance & width panners are implemented in Reaper, that's a really good example.

**Comment by MarcBoule** [comment]
We will consider this, we had even discussed it in the initial development stages of the mixer, so it would make sense to add it. It would have to be in the track menus though, since there is no room in the panel of the module.
Cheers!

**Comment by johnnovak** [comment]
Yeah I think that would be a good compromise. It's just that sometime you would like to narrow the stereo field of a reverb, or when you create a "stereo oscillator" by patching two different OSCs in the L and R channel, it would be nice if you could narrow the stereo width without resorting the external modules. Thanks! :)

**Comment by MarcBoule** [comment]
Stereo width sliders have been added in the track label menus, and we will soon add them in the aux label menus also, to handle the aux returns.

**Comment by MarcBoule** [comment]
We added stereo width to the aux-label menus also. We're going to be putting up builds soon in the releases, and it should make it into the plugin library in the next week or two. Thanks!
https://github.com/MarcBoule/MindMeldModular/releases/tag/v1.1.4b
