### ISSUE TITLE
Request: dim mode enhancements

### ISSUE THREAD

**Issue by johnnovak** [MarcBoule/MindMeldModular#18]
You could make the dim mode a bit fancier perhaps.

1. For a start, the dim amount could be made configurable in the context-menu.
2. You could also implement "dimmed solo" mode, where the soloed channel is at full volume, but the other channels are dimmed instead of muted. However, this might complicate the other mute on solo behaviours. Just something to consider, it would be a cool feature :)

**Comment by MarcBoule** [comment]
Hi,
The dim amount is in fact already configurable, it's located in the master's context menu (right-click the MASTER label). The second idea would be really neat, but here might be many repercussions and strings attached to this such that it is not trivial to implement, so we'll have to thing more about it. Thanks for the suggestion!
Marc

**Comment by johnnovak** [comment]
Cool, didn't know that it was configurable already! Yeah, solo dimming would be really cool but I guess it could complicate things quite a bit, so maybe it's not worth it after all.
