### ISSUE TITLE
Request: handle poly inputs

### ISSUE THREAD

**Issue by johnnovak** [MarcBoule/MindMeldModular#19]
It would be useful if you could directly connect poly cables to the input of a track and poly channels 1 & 2 would be routed to the L & R inputs automatically.

Use case: I want to filter a stereo signal through a polyphonic filter, so I merge my L and R channels before the filter into a poly cable. But I cannot connect the poly out of the filter to a mixer track directly, I have to use a split which is incovenient.

I think this would be a simple to do and useful enhancement.

**Comment by Torinbob** [comment]
Hi John,

Thanks for your suggestion.

The problem with this is that we already do handle poly inputs but in a different way - poly summing. You can send up to 16 poly channels into a single MixMaster input and they will be summed - but they will be summed to mono and as I understand it you want just channels 1 + 2 to be treated as a stereo signal.

I'm afraid you will need to use a Split for this - sorry.

best,
Steve

**Comment by johnnovak** [comment]
That's cool, it just seemed like a common enough use case to me, but it's no big deal. Maybe you could introduce a context menu option for this in the future (e.g. "Sum all channels (default)" and "Use channels 1 & 2 as left and right input").

**Comment by Torinbob** [comment]
Hi John

Just to let you know that the next version of MM that will be hitting the library soon includes your request.

The is now a 'Poly input behaviour' option in the track menus with 2 options:
• Sum each input (L, R) 
   - which results in a sum to mono if there is only a L input and a sum to stereo if there are both L and R inputs. (This is how it worked before)
• Sum to stereo (L only) - this sends odd channels of the L poly input Left and even channels Right - which should mean you no longer need your Split :)

best
Steve

**Comment by johnnovak** [comment]
Great, thanks for that :)
