### ISSUE TITLE
why does the mixer output negative voltages?

### ISSUE THREAD

**Issue by KarateSnoopy** [MarcBoule/MindMeldModular#2]
See these pictures which compare it to VCV's mixer.  For some reason the output is negative (using all defaults) 

![p1](https://user-images.githubusercontent.com/7510226/67165510-d2b15300-f33a-11e9-86af-ba4f99d57a3d.PNG)
![p2](https://user-images.githubusercontent.com/7510226/67165511-d2b15300-f33a-11e9-93d2-7d710f2901c9.PNG)

**Comment by MarcBoule** [comment]
It looks like you are using the "-" output to go to MixMaster, and the "+" ouput to go to VCV Mixer, so this would appear normal, if you move the blue cable in the first setup to the other 12 output, i.e. one jack to the right on the ML Constants, then it should be positive.
