### ISSUE TITLE
Unable to select individual colors for VU meters

### ISSUE THREAD

**Issue by technochitlin** [MarcBoule/MindMeldModular#20]
Even after selecting "Set per color" in the right-click menu, setting a color for a VU meter colors all of them, not just the one selected. It also resets the Display colors to whatever was chosen, regardless of what it was set to before. Both mixers exhibit this behavior.

This used to work correctly but at some point quit working- I cannot specify which release.

I am using a Windows 10Pro setup.

**Comment by MarcBoule** [comment]
Hi,

I can't reproduce this. Can you give me the exact steps you are taking, after dropping a fresh instance of the mixer in a patch?

Here's what I tried:

1. Drop a MixMasterJr in the patch
1. Send a sine wave from VCO-1 into the first 4 channels' L inputs
1. Right-click module and set *Display colour* to *Green*
1. Right-click module and set *VU Colour* to *Set per track*
1. Right-click track 1's label and set its *VU Colour* to *Cyan*
1. Right-click track 3's label and set its *VU Colour* to *Blue*

Everything appears normal. 

If you can report something like this that re-creates the problem exactly, we would very much like to know the steps. Are you using the v1.1.4 of plugin, as installed from the plugin library?

Cheers,

Marc

**Comment by technochitlin** [comment]
[Winces, smiling bashfully] I wasn't right-clicking ON THE LABEL. Operator error, as these things usually are.

Thanks!
