### ISSUE TITLE
EqMaster kind of "autogain" feature

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#21]
Hi Marc! What do you think - is that possible to implement a link between channel bypass (and global bypass as well) and gain knob? Now what we have - Let's suppose I have set the gain knob up to +7 just because before I reduced too much frequencies and I wanted to compensate it then. And then if I will press bypass - the gain will remain the same +7 db but it will overdrive my output, as well as global bypass will overdrive everything. So I just ask you to link somehow active bypass to automatically 0 gain, that will be perfect to estimate A\B properly. 
Thanks for EqMaster btw, this is amazing peace of software EQ!

**Comment by MarcBoule** [comment]
Hi Artem, definitely a great suggestion, we will do this!
Thanks for the issue (and the kind words) :-)
Cheers!

**Comment by MarcBoule** [comment]
It has been done in the source code, and we'll be putting up new builds very soon. Thanks again!
