### ISSUE TITLE
EQMaster: Analyzer pre/post when Volume CV in use

### ISSUE THREAD

**Issue by mattcollier** [MarcBoule/MindMeldModular#22]
Hello!  I was very excited to try out the pre-release of the EQMaster.  I built from master 2b29c11be036951f719e24f9741d4dce360ef636

This screenshot shows that the analyzer in the EQ is displaying the pre-fader input from VCF before the CV controlled volume.  This is cool, but I would expect that I would have some option for viewing post fader.  The pre and post options on the analyzer outputs are the same.  

Am I overlooking something?

![Screenshot from 2020-01-26 15-50-32](https://user-images.githubusercontent.com/902041/73141583-b3217900-4053-11ea-8643-b3b18b3a91a8.png)

[eq-pre-post.zip](https://github.com/MarcBoule/MindMeldModular/files/4114341/eq-pre-post.zip)

**Comment by Torinbob** [comment]
Hi 

The EQ is connected to the inserts on the mixer and inserts are always pre-fader on mixers - therefore the is no way of seeing the post fader output on the analyser.

The pre/post settings on the analyser are pre EQ and post EQ - nothing to do with the fader.

Hope that helps.

**Comment by Torinbob** [comment]
If you want to see the post fader output on an analyser you could hook an analyser up to the direct outs for that (make sure they are set to post-fader or post mute/solo in MM global settings)

**Comment by mattcollier** [comment]
@Torinbob thanks for the clarification.  There are some interesting ideas about how sends and plugins are ordered in Ardour, see the mixing section here: https://ardour.org/features.html

The UI on EQ Master is beautiful.  It has worked very well during my first 2 hour session of playing with it with Rack v1.1.6.
