### ISSUE TITLE
Issue with Linux build and linkage

### ISSUE THREAD

**Issue by Chaircrusher** [MarcBoule/MindMeldModular#23]
Hey, love MindMeldModular, but....
Looking at the beta version for 1.5 it has the Shared Object disease:

```gozgo /home/kwilliams/.Rack/plugins-v1/MindMeldModular $ ldd plugin.so
./plugin.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./plugin.so)
./plugin.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./plugin.so)
	linux-vdso.so.1 =>  (0x00007ffcb7fd5000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fefb37fa000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fefb34f8000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fefb32e2000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fefb2f14000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fefb3dff000)```

I am running an older Linux distro and can't update it.  The released version of MindMeldModular works fine, meaning that it was compiled in way conforming EXACTLY to how Andrew says you should do Linux builds.  The beta is ... not.

Thanks!  PS I tried the new EQ stuff on Windows and thought it was amazing.

**Comment by MarcBoule** [comment]
Hi, I believe it is because we leave this line uncommented by default, can you try uncommenting line 6 in our makefile 
# FLAGS += -include force_link_glibc_2.23.h
and then comment line 5, and see if that fixes things?

**Comment by MarcBoule** [comment]
My apologies, I just realized you were not building it yourself, but instead using the build we put in the releases.

I'll try to get a new build in very soon that should work in your distro.

**Comment by Chaircrusher** [comment]
I actually downloaded and built it and it worked perfect. There's one compiler warning, which is annoying but it isn't a real problem.
