### ISSUE TITLE
Request: Fader Peak

### ISSUE THREAD

**Issue by Cordoha** [MarcBoule/MindMeldModular#24]
Just asking for a request

It'd be awesome to have Fader Peak indication. When the gain is too high, the VU meter stays red or whatever colour indicated. The VU meter either gets clicked to remove the indication, or it auto removes after a while until it peaks again. I'd rather it not be auto-removed because the indicator is handy for when you need to turn the gain lower. Clicking it to remove would be great though. A lot of DAWs have this feature.

Thank you for the plugins! They're amazing.
Justin

**Comment by Torinbob** [comment]
Hi Justin

First off, I'm not sure I completely understand your request...

The Master VU on Mixmaster already turns red for a couple of seconds when it peaks above 0dB in hard clip mode or above 1.58dB in soft clip mode.

All the VUs also already have a peak hold feature which shows the maximum peak reached.

If you are talking about a text readout of the peak which can then be clicked to remove it (like some DAWs have), then that is something we considered but decided there wasn't really enough room to add it - having such.a fully featured mixer in Eurorack format does unfortunately mean some compromises have to be made.

Its worth checking out the manual to see the difference in how track VUs and the Master VU are calibrated. In short, unless a track VU is hitting above +6dB, it is not clipping.

thanks
Steve

**Comment by Cordoha** [comment]
Yeah, alright. Thanks for the input.
