### ISSUE TITLE
Request: EQ Master: Push/Pull Analyser shelf

### ISSUE THREAD

**Issue by Cordoha** [MarcBoule/MindMeldModular#25]
Pushing and pulling the Active Equalizer settings on the Analyser itself. The coloured dots that specify which shelf. Allowing the settings to be readjusted accordingly. Harrison plugins have this feature.

**Comment by MarcBoule** [comment]
Yes, we have thought of this also, and this is somthing that might be done in the future. Thanks!

**Comment by Cordoha** [comment]
Cool, thanks for the input. :D
