### ISSUE TITLE
FEATURE REQUEST: Mix junior with built in aux sends

### ISSUE THREAD

**Issue by paulrobertpine** [MarcBoule/MindMeldModular#26]
Hello, 

I love your modules. Please consider making another version of the MixJr with 2 aux sends instead of the group busses. 

Thanks, 
Paul

**Comment by Torinbob** [comment]
Hi Paul,

Happy to hear you are enjoying the modules - thank you!

We did consider having only 2 aux sends on the original junior but it didn't work very well design wise.

I think it's unlikely we'd make a version like you suggested - there are already other options in VCV for mixers that are configured like that. When we do have some more time to work on MindMeld stuff, it will be for completely new modules. Any updates to the mixers themselves are likely to be very minor.

best,
Steve

**Comment by paulrobertpine** [comment]
Hi thanks for Getting back to me,

That’s fair, thanks for considering it

Paul
