### ISSUE TITLE
Request: Desaturated VU meters when muted on MixMaster

### ISSUE THREAD

**Issue by unlessgames** [MarcBoule/MindMeldModular#27]
Hello!
The title says it all, I'd find this helpful, especially to avoid accidental unmuting of something loud and identifying channels more easily in general.
Thanks for this anyways, instant default mixer!

**Comment by Torinbob** [comment]
Hi,

Glad to hear you are enjoying the mixer!

This is a great idea! Can't promise anything yet but something we will definitely take a look at.

Thanks for getting in touch about it.

Best,
Steve

**Comment by Torinbob** [comment]
Work in progress :)

https://youtu.be/WlNZhe1Yx6o

**Comment by unlessgames** [comment]
Just pulled and built it and it's already perfect! :o 
Thanks for the quick response!

**Comment by MarcBoule** [comment]
This is considered done and it will be part of the next update, so closing the issue. Thanks for the suggestion!
