### ISSUE TITLE
panning and volume

### ISSUE THREAD

**Issue by KarateSnoopy** [MarcBoule/MindMeldModular#3]
Be aware that when putting 1.0 volts through a mono channel and centering it, it outputs 1 and 1 as expected 

but when hard panning it to one side, it outputs that as 1.421 and 0.  So it the effect is that panned input is a louder than non-panned.  Not sure if this is a bug or not, but be aware of this

![p3](https://user-images.githubusercontent.com/7510226/67165637-7f400480-f33c-11e9-96ce-97dbbd76625f.PNG)

**Comment by MarcBoule** [comment]
This is expected behavior as the default mono panning law in the mixer is Equal power (aka +3dB boost). 

If you want it to stay at the same level, select "+0dB (no compensation)" in the module's right-click menu, under "Mono pan law".
