### ISSUE TITLE
MixMaster "BASS MONO" enhancement in the track's menu

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#30]
Hey Marc (and Steve of course!) and here is another suggestion from me) Totally ripped off from ableton's utility but sometimes this is pretty needed right in VCV due to the nature of super wide stereo or stereo-poly signal. So in the ableton we have Bass mono switch from 0hz to 500hz. Sometimes it's not enough when dealing with superwide supersaws or whatever super- so I'd suggest you (if you like the idea of course - a strip control below stereo-width strip btw) the range from 0hz to 1khz. And yeah EQmaster doesn't have (who knows maybe just at the moment?) M|S signal processing so the side bass cutoff would be pretty nice feature for making mono compatible but huge basses. Cheers!

**Comment by MarcBoule** [comment]
Hi Artem, just wanted to say I saw the issue, but I'll need to wait for Steve's input on this.

**Comment by MarcBoule** [comment]
Just to update this issue, we are working on it, but the required filter is quite difficult to make (efficiently at least), so this will take more time than expected.

**Comment by MarcBoule** [comment]
This has now been implemented and will be released soon. Cheers Artem!
