### ISSUE TITLE
can we get light color scheme

### ISSUE THREAD

**Issue by modman2019** [MarcBoule/MindMeldModular#31]
This would be useful for those who like uniformity if using white modules.

**Comment by Torinbob** [comment]
Never say never but it’s unlikely to happen anytime soon I’m afraid. Busy working on other module designs and creating a light skin is quite a lot of work just to satisfy some uniform colour OCD :)

**Comment by ContemporaryInsanity** [comment]
@modman2019 you can edit the svg files yourself to get a light background.

**Comment by modman2019** [comment]
can you provide a quick step by step how to do that using GIMP?

**Comment by ContemporaryInsanity** [comment]
Use Inkscape, if all you're doing is changing the background colour that's quite straightforward, have a look on youtube for Inkscape tutorials.
