### ISSUE TITLE
mixmaster 24tracks?

### ISSUE THREAD

**Issue by matthleg** [MarcBoule/MindMeldModular#33]
hello,
 are you not thinking to make an other version of your mixmaster (and auxspander and eqmaster)
with more tracks? Now I have a patch with 20 tracks and your modules are so nice I don't know how to work without them...
Have a nice week.
Matthieu

**Comment by Torinbob** [comment]
Hi Matthieu,

Thanks for the kind words.

We have no immediate plans to make a 24 track version but we may take a look at it at some point in future.

In the meantime you can use the chain input on MM to mix the output of another mixer to it. (probably best to make sure Chain input is set to pre-master fader in global options to allow the master fader on the main mixer to control the level of both mixers. 

You can even use small utility mixers to enable the mixers to share the same Aux FX. I used the 2hp unity mixer from Quantal Audio in the patch below so the 2 mixers share reverb and delay. 
You'll probably want to keep the master fader of the sub mixer at 0dB as when you reduce the level of that fader, the Aux sends still go out at their original level - we are looking to see if something can be done about that in a future update though such that FX send levels are reduced in line with the master fader level on the sub mixer.

The one thing this solution does not allow for is linking the mute/solo functionality between the mixers - which would be very complicated to do.

<img width="1576" alt="Screenshot 2020-04-27 at 14 03 43" src="https://user-images.githubusercontent.com/41232273/80381345-bae1fb00-8898-11ea-8c54-a31fc132534f.png">

**Comment by MarcBoule** [comment]
We added an option as described above so that FX send levels are reduced in line with the master fader level on the sub mixers, so chaining is the best we can do for now.
