### ISSUE TITLE
Bass master initialize poly second poly behavior when bypassing

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#35]
Hi Marc & Steve, thanks for implementing long waited Bass master!) Here is an issue - while in Poly sum to stereo mode bypass just disabling right output. So it's hard to estimate changes bypassing that way. 
Cheers!

**Comment by MarcBoule** [comment]
It took a while, but we got it :-)
Can you pull and try now please? 
I think it should be fixed.
Thanks!

**Comment by vcvrackideas** [comment]
> It took a while, but we got it :-)
> Can you pull and try now please?
> I think it should be fixed.
> Thanks!

Thanks, it's working now! BTW Marc, I can't compile it on os x catalina. Shows error something like -  rack simd hypot in Eqmastercommon.hpp and can't build that

**Comment by MarcBoule** [comment]
That's weird, are you sure you have the lastest Rack source (or SDK)? Steve is on Mac also and he has no problems (me neither, but I have a much older Mac).
