### ISSUE TITLE
SUGGESTION: Copy values (i.e. level fader) from channel to channel.

### ISSUE THREAD

**Issue by Chaircrusher** [MarcBoule/MindMeldModular#36]
This is something I do a lot: right click a fader, copy the value (ctrl-C) and then right click another fader and paste the value to set it to the same level.

It would be great if there was a way to set the level of a group of faders. I'm really foggy on what the best user interface for this would be. Maybe a tiny button you'd tick to group faders? A key chord (ctrl-alt left-click on a control, then ctrl-alt right-click to paste to the new control).

Just putting a bug in your ear. I'll also make a suggestion on the Rack github, because it would be great if this worked across the whole application.

**Comment by MarcBoule** [comment]
Hi,

The option is already there :-) It's called Linked faders. If you **alt+click** a fader, it will be linked with other faders that have been alt-clicked, and then you can change one of them and they all move together. So in your case, they would have to be all set to the same value, say their initial 0dB, and then after they are all linked, set one of them to -6 and they will all go to -6dB. After that, to unlink them, **shift+alt+click** any one of them and they will all automatically be unlinked.

![image](https://user-images.githubusercontent.com/33604154/83917512-0a8fce00-a745-11ea-960c-d8f22880d92e.png)

Cheers!

**Comment by Chaircrusher** [comment]
Cool. I guess RTFM is always good advice!
