### ISSUE TITLE
Request: option to disable smoothing for volume automation in MixMaster(Jr)

### ISSUE THREAD

**Issue by MaZe6K** [MarcBoule/MindMeldModular#37]
Hi there!
I wonder if you might be willing to add the option to disable the smoothing of the volume automation on your Mixers (using the "V" inputs). This would sometimes come in handy to directly use channels as VCAs, or for more precise sidechaining of channels and group busses or other fast amplitude modulation.

**Comment by Torinbob** [comment]
Hi

This is something we are already working on right now.

The next release will have a "Linear VCA" option for the Vol CV inputs with no smoothing or scaling for exactly the purpose :)

**Comment by MaZe6K** [comment]
very cool, thanks!

**Comment by Torinbob** [comment]
Hi,

This is now implemented int he latest build on our releases page.

In global settings go to Vol CV Inputs > Linear VCA. Please try it out and let us know what you think. 

thanks
Steve

**Comment by MaZe6K** [comment]
it doesn't seem to have hit the releases page yet... you mean this one, right?
https://github.com/MarcBoule/MindMeldModular/releases

**Comment by MarcBoule** [comment]
The github release is maked as being 5 days ago, but right below you should see that the build files themselves were updated yesterday, so if you downloaded today, you should have the latest version.

**Comment by MaZe6K** [comment]
oh ok... :) thank you! seems to work nicely, tested the vca on one channel and am very much enjoying clean sidechaining now! :)

**Comment by MarcBoule** [comment]
Excellent :-) Cheers!
