### ISSUE TITLE
Meld-like device for all poly control inputs of mixer and auxspanders

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#38]
Hi guys! What do you think on making device that similar to Meld module but with panel onboard corresponding to poly cv inputs like at the left side of mixers and at the right side of auxspander? Of course with changeable panels in right click menu for the each input. I mean PolyMerge is maybe enough for it but it's a bit annoying to keep in mind all internal connections in polyphonic inputs.
Cheers!

**Comment by MarcBoule** [comment]
New tricks :-) 
The Meld module now has a bunch of extra panels for use as poly CV input, as you described.
Best check with Steve though if putting it in a video before we announce it, just to be sure.

![image](https://user-images.githubusercontent.com/33604154/85350320-d64f3800-b4ce-11ea-8bca-cba80956db4f.png)
