### ISSUE TITLE
Option that can transform Jr version to big one

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#39]
Ok it sounds a bit weird I know but maybe it's possible) The reason I'm asking for it is rack wideness versus 8 inputs. So for example I may keep in my template 16inputs version of mixer but most of the time I'm finished just with less than 8 tracks and vice versa - sometimes I need 9 to 16 tracks with the same AUX busses (otherwise I'd go for chaining mixers). And maybe your modules or Rack allow to do some internal changes in modules with keeping settings and inputs on its places? Just curious for some kind of hack) It would be a huge time saver feature.

**Comment by Torinbob** [comment]
Hi Artem

You can chain mixers and share the same Aux - I posted a picture of how to patch it in an earlier closed thread where someone requested a 24 track version of the mixer.

The only thing you don’t get with this method is solo across the 2 mixers.

I wonder if there is a way of right clicking on the Jr and having a ‘change to 16 track’ function (and vice versa) - not sure if possible or practical but I’ll speak to Marc.

**Comment by Torinbob** [comment]
I've spoken to Marc and it is not straightforward at all (would be a complete nightmare in fact!). The best we might be able to do is a custom variation on presets such that you could save a preset from the 16 track and open it in the 8 track and vice-versa. This would keep all the mixer settings but not the connections. It's something we might take a look at in a future version.

**Comment by technochitlin** [comment]
> I've spoken to Marc and it is not straightforward at all (would be a complete nightmare in fact!). The best we might be able to do is a custom variation on presets such that you could save a preset from the 16 track and open it in the 8 track and vice-versa. This would keep all the mixer settings but not the connections. It's something we might take a look at in a future version.

I know this is a closed topic, but double upvote on this idea- reconnecting the cables is fairly trivial, reproducing all the levels and settings is a PITA. Actually I tried the preset route before logging here, but as you already know it doesn't yet work.

My 2p

**Comment by MarcBoule** [comment]
Hi @vcvrackideas and @technochitlin this has been completed and can be tested by pulling and building or by getting the builds here:
https://github.com/MarcBoule/MindMeldModular/releases/tag/v1.1.10b

There's a new menu option in the top section of the module's menu (both in MixMaster and AuxSpander) and all you have to do is copy in one mixer (8-track for example) and paste in the other (16-track for example). It won't move the cables, but as mentioned, at least it takes care of the ugly business!

**Comment by technochitlin** [comment]
Wonderful! Thanks so much! A soon as I get power back I'll check it out! (Zeta victim)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarcBoule** [comment]
Oh! Hope things will be ok, good luck!

**Comment by technochitlin** [comment]
Just tried it (power back on, yay!) copying both the mixer and auxexpander in both directions. Well done, it works exactly as one would think it would. Best mixer ever!

**Comment by MarcBoule** [comment]
Thanks! Happy to see you have power back :-) Enjoy!
