### ISSUE TITLE
Linked Faders

### ISSUE THREAD

**Issue by Ananda6262** [MarcBoule/MindMeldModular#4]
Link faders jump when returning to patch...
![VCV Rack v1 1 5 - Orca vcv 10_22_19 5_08_44 AM](https://user-images.githubusercontent.com/37520449/67251300-44e57d00-f48c-11e9-8218-ecb05f1130cb.png)

**Comment by MarcBoule** [comment]
Thanks, currently working on this :-) 
Will let you know when it's fixed.

**Comment by MarcBoule** [comment]
Should be fixed now, the builds were updated in the Releases section. If you try it and see anything misbehaving, please let me know. Thanks Ananda!
