### ISSUE TITLE
MixMaster jr - adjusting hi-pass on aux causes loud glitches

### ISSUE THREAD

**Issue by espenstoro** [MarcBoule/MindMeldModular#40]
Greetings!
Adjusting the hi-pass on the aux channels will sometimes make loud clipping square wave sounds. Doesn't matter what is connected. Needless to say, it scared the fertilizer outta me. 
Seems like it happens when I activate hi-pass, I can adjust it afterwards without problems, as far as I can tell.
This occurred after updating to 1.1.7 today, previous version never did that. Rack 1.1.6, Windows.

**Comment by MarcBoule** [comment]
Fixed, if ever you're in position to try out the new version, I have put up new builds here:

https://github.com/MarcBoule/MindMeldModular/releases/tag/v1.1.7b

Thanks again Espen, sorry about that one!

**Comment by espenstoro** [comment]
Thank you so much for the super quick fix, sir, although I wasn't exactly sure how to repro. Will test shortly.
Oh man, if this mixer dies, I might as well quit Rack. No going back to the old ways. :smile:
