### ISSUE TITLE
An option to disable (mute) direct outputs for those channel which was been routed to the groups

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#42]
Can you add this one? Especially useful in the case of layering or so stuff. So then it will be no mess in the multitrack project and only groups stereo file(s) would be available of the channels that was been routed to the groups.

**Comment by MarcBoule** [comment]
More things to test Artem, that the price you have to pay for making the suggestions, haha! :-)

![image](https://user-images.githubusercontent.com/33604154/85930608-ddd65e80-b88b-11ea-9903-9060ec91dd2f.png)

**Comment by vcvrackideas** [comment]
Ok, for sure! Just did a quick test without even listening what's going on - got Nysthi Polyrecorder and chose consolidating tracks and separate stereo tracks to one folder. There was 5 inputs, 2-3 to group one and 4-5 to group two and in the end of the testing I've got 3 stereo files in recorded multitrack folder! It's a wonder, thanks. Many ways now to do a layering inside mixmaster without worries then in Ableton due to peaking levels or just unwanted tracks!
