### ISSUE TITLE
Option to ignore fader position for yellow arrows (absolute CV mode) 

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#45]
Do you think guys it would be useful to have this option (probably per track basis)? just in real word of faders "automation" can be higher and lower from initial fader position but now in mix masters I can modulate volume only below the faders...

**Comment by Torinbob** [comment]
Hi Artem,

This could lead to some potentially nasty clipping if fader is high and positive CV is added. I think using fader to specify max level and then using CV to control level up to that point is the best and safest solution so we are going to say no on this one I'm afraid....
