### ISSUE TITLE
Lights off request

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#49]
Great to see EQ MASTER lighting up.  Could we have the orange VCA markers (next to faders) and knob indicator collars as lightwidgets too please?  Maybe also mute & solo buttons?

Finally thanks so much for by far the best mixer in VCV.

**Comment by MarcBoule** [comment]
We did the fade and cv pointers, on the faders, but for those other ones, they use Rack's button and knob constructs, and would be a lot of trouble to reimplement as light widgets, so I don't think we will get into that. Cheers!

![image](https://user-images.githubusercontent.com/33604154/88098721-3980c880-cb68-11ea-9018-b24e7bcc9fad.png)
