### ISSUE TITLE
Feature Request: Incorporate Air Windows Console processing in Expander?

### ISSUE THREAD

**Issue by Chaircrusher** [MarcBoule/MindMeldModular#50]
This is not a complaint about your summing bus - it sounds great. But the RackWindows Console processing is a different, really attractive sound.

I logged this [feature request](https://github.com/n0jo/rackwindows/issues/7) in the RackWindows github.  But it occurred to me that you're uniquely situated to streamline using RackWindows Console. either as an option on Mixmaster, or as an expander.

To use the Console module right now, I have to route the direct outputs to a VCV Split module, and then route mono channels into Console. It takes 2 splits to work with Mixmaster Jr - one for 1-8 & Grp/Aux direct outs.  In this mode -- where the direct outputs are summed by Console -- the channel meters are inactive as well.

I'm a very happy customer of Mindmeld MixMaster and its other expanders, but I'm excited by the idea of having other summing DSP available.

**Comment by MarcBoule** [comment]
Closing, as per discussion here:
https://community.vcvrack.com/t/rackwindows-mindmeld-mixmaster-best-way-to-use/10611/2
