### ISSUE TITLE
MixMaster feature request: Use log fade in, exp fade out simultaneously

### ISSUE THREAD

**Issue by espenstoro** [MarcBoule/MindMeldModular#51]
Hi. I thought of something that would be musically very useful. When fading in, due to the nature of the db scale, it's usually better to use a logarithmic curve, just as it'll be good to use exponential for fade out, otherwise it can seem pretty abrupt, unless you use extremely long fade times.
What if it can be set to use log for fade in, then exponential for fade out? The alternative now is to go in and change it manually for every fader, unless I'm missing a setting that I can't find (quite possible). I think it could be very useful.

Not a high priority issue at all, but something to consider, maybe?

**Comment by MarcBoule** [comment]
Hi Espen, I think the option you are searching for is in the module's main menu, under _Fades_ there is the _Symetrical_ option which can be turned on or not.

**Comment by espenstoro** [comment]
D'oh! I knew it. Gotta RTFM more often.

Thanks for the tip. Problem solved. :)
