### ISSUE TITLE
Mixmaster crash on solo

### ISSUE THREAD

**Issue by Eurikon** [MarcBoule/MindMeldModular#52]
Hi Marc, sorry to bug your neat empty issue list :)

I think I stumbled on something,
haven't tried to replicate it with an empty patch as I am in the middle of a project.

But the crash is consistent each time I click solo on a certain track.
The same track has fade engaged as well, maybe something that has to do with it.

I will send you the patch through forum message box. 

Cheers,
Latif

**Comment by MarcBoule** [comment]
Hi Latif, all good :-) we indeed like to keep the issue list empty, but if something is coming up, that's what it's for, and we'll look forward to trying your patch. Cheers!

**Comment by MarcBoule** [comment]
We've been able to get the crash, but when I run the patch in the debugger, here's what I get on the crash:

```
Thread 9 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 6096.0x13b4]
0x000000002007ed1e in plugin!_ZN11Simpliciter3eocEi ()
   from C:\msys64\home\mboule\Rack\rdev\Rack\plugins\NYSTHI\plugin.dll
(gdb) bt
#0  0x000000002007ed1e in plugin!_ZN11Simpliciter3eocEi ()
   from C:\msys64\home\mboule\Rack\rdev\Rack\plugins\NYSTHI\plugin.dll
#1  0x00000000200a93aa in plugin!_ZN11ny_file_osc4stepEv ()
   from C:\msys64\home\mboule\Rack\rdev\Rack\plugins\NYSTHI\plugin.dll
#2  0x000000001fee298d in plugin!_ZN11Simpliciter7processERKN4rack6engine6Module11ProcessArgsE ()
   from C:\msys64\home\mboule\Rack\rdev\Rack\plugins\NYSTHI\plugin.dll
#3  0x000000000049a0c0 in rack::engine::Engine_stepModules (threadId=0,
    that=<optimized out>) at src/engine/Engine.cpp:269
#4  0x000000000049c8b0 in rack::engine::Engine_step (that=0x537dcd0)
    at src/engine/Engine.cpp:346
#5  rack::engine::Engine_run (that=0x537dcd0) at src/engine/Engine.cpp:448
#6  rack::engine::Engine::<lambda()>::operator() (__closure=<optimized out>)
    at src/engine/Engine.cpp:482
#7  std::__invoke_impl<void, rack::engine::Engine::start()::<lambda()> > (
    __f=...) at C:/msys64/mingw64/include/c++/8.3.0/bits/invoke.h:60
#8  std::__invoke<rack::engine::Engine::start()::<lambda()> > (__fn=...)
    at C:/msys64/mingw64/include/c++/8.3.0/bits/invoke.h:95
#9  std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::_M_invoke<0> (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/8.3.0/thread:244
...
```

If we look at the first couple of lines, we see that Simpliciter appears to have caused the crash. I can't explain why it's happening when you press solo, but Steve was able to get the crash just by deconnecting some wires, so I really don't think it's a MixMaster issue. Probably a memory leak or something... so I don't want to put the blame on @antoniotuzzi but might be worth pinging him on this at least.

**Comment by Eurikon** [comment]
Ah, thanks a lot! That is very helpful. 
I was suspecting Simpliciter, but when I clicked on solo buttons, i drifted of to Mixmaster..

I will let Antonio know about it, as well.:)

**Comment by MarcBoule** [comment]
Excellent, take care Latif!
