### ISSUE TITLE
Higher Contrast Dark Theme

### ISSUE THREAD

**Issue by schuster-rainer** [MarcBoule/MindMeldModular#53]
Would you accept a MR for a even dark theme? I've been patching the current rack version for my personal usage including the fundamentals and some other modules. So if you would merge this into your branch, I'd actually do the work of properly integrting it completely.

<img width="1792" alt="VCVRack - Dark Theme" src="https://user-images.githubusercontent.com/67356/95029373-11553000-06a8-11eb-9618-75349fc72138.png">

**Comment by MarcBoule** [comment]
Hi, thanks for the proposal, but Steve and I prefer to keep just one color theme, so we will unfortunately not take you up on your contribution. Cheers!
Marc

**Comment by schuster-rainer** [comment]
Totally fine for me. Are you fine with having a public repository with the modifications in the svgs, because it's derivative work. Otherwise I'm going to create a private mirror for this. Thanks for your feedback. Keep up your amazing work.

**Comment by Torinbob** [comment]
Hi

Steve here - I think I'd prefer if you kept the repository private for now please as the SVG graphics and logo are all copyright. I have no problem with you modding them for your own personal use but please don't distribute publically.

thanks
