### ISSUE TITLE
Enhancement suggestion: Stereo spread per channel

### ISSUE THREAD

**Issue by Chaircrusher** [MarcBoule/MindMeldModular#54]
Of course it would be cool to modulate this but if there was a slider (like fade time) in the channel properties menu, that would be valuable.

**Comment by Torinbob** [comment]
Hi Kent

We already have stereo width per track (appears in track menu when there is a stereo input) - this allows stereo width up to 200%

Or do you mean spreading poly signals across the stereo field?

**Comment by Chaircrusher** [comment]
You're right! Sorry! I'm an idiot!
