### ISSUE TITLE
Move tracks automatically in EQ when Mixer tracks move

### ISSUE THREAD

**Issue by corrision** [MarcBoule/MindMeldModular#56]
hi, marc.
thank you for making fantastic modules ! 

so, when moving a track to a different track on mixmaster,
the eq settings in eqmaster dont follow.

this would be a nice addition

**Comment by MarcBoule** [comment]
Hi, thanks :-) This would require a fair amount of work, so unfortunately it won't be possible in the near future, but it does make a lot of sense to eventually add this. Cheers!

**Comment by corrision** [comment]
Yeah, fair enough, I can only imagine how much programming that would take!

**Comment by MarcBoule** [comment]
Now available, closing
