### ISSUE TITLE
Feature Request: about a FinalEQ

### ISSUE THREAD

**Issue by smok-e** [MarcBoule/MindMeldModular#57]
as Marc asked I put this FR here:

I would like to ask you about The EqMaster, if it would be possible to make a stripped down version of it as FinalMaster (FinalEq), it would just be a stereo version of it. that can equalize the final output of a mix. I use it this way now, but need to merge the outs of MixMaster to route them to the first two channels of EqMaster and split them after this again to send them to a mastering limiter or something like this.

I really like the visual representation of sound in the EqMaster UI and I would like to use it on my “Masterbus”.

thanks

**Comment by MarcBoule** [comment]
I discussed the possibilities with Steve, and we have a few ideas, but first we will be finishing our current module, so it will take a few months before we can get to it. Cheers!
