### ISSUE TITLE
Suggestion: VU meter in AuxSpander ID bar

### ISSUE THREAD

**Issue by dowodenum** [MarcBoule/MindMeldModular#58]
Hey, love your mixer, it's in my template and it'll probably stay there for a long while.

I was thinking a neat feature would be to copy the VU meter effect on each channel to the spot where the channel name/number comes up, in a horizontal format instead of vertical, and maybe with some partial-opacity so you can still read the field. This would really help with identifying which channel is which, at least for those who don't name their channels.

Maybe something like this:
![](https://i.imgur.com/k1rm63l.png) 

Anyway, just an idea. Thanks for your hard work, I'll be donating soon!

**Comment by MarcBoule** [comment]
Hi, 
thanks for the encouraging words and the idea! I talked it over with Steve, and both for techincal reasons (CPU load, expander mechanism) and for UI reasons (consistency across modules), I don't think we will go down that route, but it's definitely an intersting concept! Good to keep in mind though :-)
Cheers,
Marc
