### ISSUE TITLE
Poly Mute doesn't toggle correctly

### ISSUE THREAD

**Issue by mikeloveridge** [MarcBoule/MindMeldModular#6]
Hi, I originally submitted this to the wrong developer.  I'm not sure how that happened, so hopefully I'm doing this correctly this time.

Hi! First, thanks for developing such a nice mixer. I'm an audio guy and find this mixer to have many of the capabilities I use in a mixer. I have some enhancement requests that I will submit separately.

The issue I'm finding is that if I use the CV-Map Midi mapper from Stoermelder and press the Mute button for a channel on my BCF2000 USB Midi control surface, the mutes occur correctly with a single press muting and another press to unmute.
If I bypass the mapper and send a poly connection to the Poly Mute input, then one press mutes, but the second press does not unmute. It takes a 3rd press to unmute and now my control surface is showing the channel as muted. So the Poly Mute input is not behaving the same as when it is controlled by the Midi Map module.
It may be that I need to edit the midi on my control surface to send different information, but it seems like it should behave the same way. I'm assuming the input to Poly Mute is looking for a high voltage to mute and low or 0 to unmute. I believe my control surface is sending a 127 to mute and a 0 to umute. I may need to put a flipflop in between the Midi module and ten merge for the Poly Mute input, but if I need to do that, I may as well use the Midi Map module and just map the mute button since that works as expected.
I am attaching images for the 2 configurations.
Using Midi Mapping
![Using Midi Mapping](https://user-images.githubusercontent.com/14959412/67352744-ad247500-f505-11e9-8c8b-558d577a1970.png)

Using Poly Mute
![Poly Mute](https://user-images.githubusercontent.com/14959412/67352773-c3323580-f505-11e9-9ec6-0e7f0f144e7f.png)

**Comment by Torinbob** [comment]
In order to be controlled by both CV and midi mapping, the mutes respond in toggle fashion to the rising edge of a trigger. First rising edge will turn the mute on, the next will turn it off.

I think the solution is to set your midi controller to output a momentary trigger when you hit the mute button rather than a latched "gate high" signal. If the controller sends a gate high, then that will turn the mute on, but the next time you press the button nothing will happen as the gate goes low and there is no rising edge to toggle the mute.

**Comment by MarcBoule** [comment]
Steve is correct, it has to be a momentary button since our mute inputs respond to rising edges. This is also how it is done on Console, and in your case, perhaps the BCF is like my Novation Launch Control where with software the button types can be changed. Good luck with the setup!

**Comment by mikeloveridge** [comment]
Thanks for the info.  Now that I will use this mixer exclusively, I will
reprogram my controller to handle this.
Mike
