### ISSUE TITLE
Feature Request: Phase Flip

### ISSUE THREAD

**Issue by z-plane** [MarcBoule/MindMeldModular#63]
Call me old-fashioned, but I like a phase flip on my channels. Would be great to add this to the channel options.

**Comment by MarcBoule** [comment]
Unless you are looking for phase flip on a single input (say only L or only R), we already have a phase flip that works at the track level. It is called "invert input" and is available in the track menus:

![image](https://user-images.githubusercontent.com/33604154/114931709-93b36f00-9e04-11eb-81b1-9f9bb62d261e.png)

**Comment by z-plane** [comment]
my bad sry!
