### ISSUE TITLE
ShapeMaster Feature request - note on NOD tooltips

### ISSUE THREAD

**Issue by Guy-sh** [MarcBoule/MindMeldModular#64]
Hey,
Amazing module! Easy purchase :)
I love the tooltips on the nodes giving you voltage information,
I was wondering if it's possible to add note value to that, because it's hard to count 
those super small semi-tones when I'm building a V/oct CV sequence...

Thanks! Great work!
Guy

**Comment by MarcBoule** [comment]
Hi Guy, this seems like a good idea, we will look into it, thanks!

**Comment by Guy-sh** [comment]
Awesome, Thanks!
I love the module, deep diving into it this weekend..

**Comment by MarcBoule** [comment]
This has been added as a channel option, and will be available in the next update.

![image](https://user-images.githubusercontent.com/33604154/116275892-03552280-a752-11eb-95d1-67342841e713.png)

![image](https://user-images.githubusercontent.com/33604154/116275918-094b0380-a752-11eb-809e-969bbd243de4.png)

**Comment by Guy-sh** [comment]
Perfect! 
Thanks Marc!

**Comment by MarcBoule** [comment]
My pleasure!
