### ISSUE TITLE
Shapemaster Pro:  Poly Gate to poly CV out ?

### ISSUE THREAD

**Issue by jpnielsen** [MarcBoule/MindMeldModular#67]
I'd like to use Shapemaster for a polyphonic anvelope/ADSR - but i can't figure it out.

My midi-CV is set to 16 note polyphony - rotate mode.
I put the MIDI-CV gate (fat cable) into the CV channel 1 on the Shapemaster.
I expect a fat (16 channel)  CV out cable from channel 1 - with a CV ouput for each of the 16 envelopes.
 
But i only get a single channel CV out - and the envelope runs only when channel 1 of the poly input is gated.

I can't find it in the docs, please explain.

Thank you

![image](https://user-images.githubusercontent.com/27916597/115951677-4315d300-a4e2-11eb-92bb-cbdba9f03f53.png)

**Comment by MarcBoule** [comment]
Hi, it's only the VCA that is polyphonic, not the enveloppe itself unfortunately. It's quite a complex module, and so having 16 playheads was not something we wanted to get into.

**Comment by jpnielsen** [comment]
I see, perhaps you will make that in a later version.  I can just split out
the gates and use 2 shapemaster with 8 similar envelopes each, and combine
to poly for the VCF.

The vcv envelope generator is poly but limited to adsr.

I reqest that you make 16 envelope clones/instances pr channel available in
v 1.1.

lør. d. 24. apr. 2021 14.38 skrev Marc Boulé ***@***.***>:
