### ISSUE TITLE
ShapeMaster feature request - copy & paste shapes across module instances

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#72]
Shape copy & paste only works within an instance of SM, could we have the facility to copy a shape from one instance of SM and paste it into another.

**Comment by MarcBoule** [comment]
This could be interesting, I'll see if we can store the copy/paste data in the clipboard, then it would work seamlessly I think.

**Comment by MarcBoule** [comment]
Ok, this works well, and it will be in the next update for ShapeMasterPro, which I don't know when will happen, but I managed to squeeze it into the update for the free version which should hit the library in a few days. If ever you want an updated Pro build, just let me know.

**Comment by ContemporaryInsanity** [comment]
'If ever you want an updated Pro build, just let me know.'

Yes please :)

Now, about those voltage range constraints... ;)

**Comment by ContemporaryInsanity** [comment]
Can you do the same for channel copy & paste too please?

**Comment by MarcBoule** [comment]
Sounds logical

**Comment by MarcBoule** [comment]
This is now done and will be in the next update.
