### ISSUE TITLE
ShapeMaster - cloacked mode request

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#73]
Hi Marc! I know you've done hardest work for implementing all kind of visualization of envelopes in Shapemaster. But today I noticed one thing - it's hard to focus on sound when there are 3 instances of shapemaster in front of my eyes and that feels like mind attacking :-) Cloacked mode in MixMaster is a nice thing to have and of course reduce the power consumption when giant patch is hitting CPU limit. Maybe it would work for Shapemaster too?

**Comment by MarcBoule** [comment]
Definitely, I think it makes a lot of sense to offer this, we'll take a look! Thanks Artem!
