### ISSUE TITLE
ShapeMaster randomisation confusion

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#74]
My randomisation settings:

Min Segments: 16
Max Segments: 16
0V ratio: 50.0%
MaxV ratio: 50.0%
Stepped & Locked to Grid-X, which is 16.

I'm expecting 8 gates randomly spread over 16 segments, but sometimes I get more, sometimes less.  I'm assuming this is a fundamental misunderstanding on my part?

**Comment by MarcBoule** [comment]
Perhaps it's our terminology that leads to this confusion. Those sliders (0V and maxV) control the probability that a generated step will be 0V or maxV, but does not work globablly on the whole shape. It's like every time a step is generated, we throw the dice to see how to generate that step, so it can very well be that more than 8 will be 0V even though the probability of each one being 0V was 50%. In other words, flipping a fair coin 16 times will not always give 8 heads and 8 tails. Steve and I are going to look at this to see if we change the terminology, or the behavior of the random code.

**Comment by ContemporaryInsanity** [comment]
Understood.  Thought I was going madder for a while there.

It would be really useful to have the facility to spread x gates randomly over y steps, I'm not aware of any module that does this.  If you are please share.
