### ISSUE TITLE
meld 1 L/R do not seem to work

### ISSUE THREAD

**Issue by ShofB** [MarcBoule/MindMeldModular#76]
I am trying to mute the grp1 on the mixer using meld and can not do it.  I can mute 3 and 4 but not 1 and 2

**Comment by Torinbob** [comment]
Hi Shof,

I just tested and it is working fine here - both with mute/solo CV set to default trigger toggle or Gate high/low (in global settings.

In the following grabs I set mute/solo CV to gate high/low so you can see the LED light up when gate is high and mute is active.

First grab - Grp1 mute off (gate low)

<img width="1529" alt="Screenshot 2021-09-13 at 09 14 31" src="https://user-images.githubusercontent.com/41232273/133048982-eea4fdda-ff39-4da8-93e1-af54abc3f9e5.png">

Second grab - Grp1 mute on (gate high)

<img width="1529" alt="Screenshot 2021-09-13 at 09 14 18" src="https://user-images.githubusercontent.com/41232273/133049029-1da5ca1c-acd7-40cc-b6d4-c84292f75edd.png">
