### ISSUE TITLE
rackv2: character width / CR/LF issues

### ISSUE THREAD

**Issue by jpnielsen** [MarcBoule/MindMeldModular#77]
![image](https://user-images.githubusercontent.com/27916597/135014941-c0669a5f-2880-41e6-9949-03292472f650.png)

On windows 10.

When I enter "1234" in a channel title field, "123" is visible - "4" is on the next line - and invisible.

I can select&copy all with ctrl-A and ctrl-C - and paste it in a VCV note with ctrl-V.

Then I see "1234".

**Comment by jpnielsen** [comment]
![image](https://user-images.githubusercontent.com/27916597/135015565-b6cb794d-df9a-49b1-85e7-ec5a3edcda8c.png)

AUXpander shows "1234"

**Comment by MarcBoule** [comment]
Super, thanks for mentioning it, looks like it will require some adjustments.

**Comment by MarcBoule** [comment]
Should be fixed now, if you would like to try, please let me know if ever it's still not working right. Thanks!

**Comment by jpnielsen** [comment]
It looks much better now.

**Comment by MarcBoule** [comment]
Super, thanks for the bug report!
