### ISSUE TITLE
rackv2 bassmaster font clipping

### ISSUE THREAD

**Issue by jpnielsen** [MarcBoule/MindMeldModular#78]
![image](https://user-images.githubusercontent.com/27916597/135016137-cdb763d2-c2c6-447a-81de-b8d5df3d5211.png)

at 4k resolution, zoom 168% - the digits are clipped

**Comment by MarcBoule** [comment]
Excellent, thanks for mentioning this, I will take a look. Some font scaling has changed in v2, and will require some adjustments.

**Comment by MarcBoule** [comment]
Should be fixed now, if you would like to try, please let me know if ever it's still not working right. Thanks!

**Comment by jpnielsen** [comment]
It looks much better now.

**Comment by MarcBoule** [comment]
Excellent, thanks for the bug report, closing.
