### ISSUE TITLE
Mixmaster V2 meters not 'illuminated' when room dimmed.

### ISSUE THREAD

**Issue by ContemporaryInsanity** [MarcBoule/MindMeldModular#79]

**Comment by Torinbob** [comment]
Hmmm - they are illuminated on my Mac version and Im sure on Marc's PC version too.

What platform are you on??

<img width="1144" alt="Screenshot 2021-10-01 at 17 41 14" src="https://user-images.githubusercontent.com/41232273/135657293-6d14edc9-0bfc-4073-b803-c1edc4c66417.png">

**Comment by ContemporaryInsanity** [comment]
Sorry, ubuntu1~18.04

![image](https://user-images.githubusercontent.com/12547379/135657613-ebbaa514-970b-468d-bb09-1e0e68dc0830.png)

**Comment by MarcBoule** [comment]
Just to make absolutely sure, are you using the latest pull of the repo? Since in an earlier version of our v2 port they were like this but it should have been fixed.

**Comment by ContemporaryInsanity** [comment]
DOH!

Apologies for wasting your time.

Thanks once more for the superb modules :)
