### ISSUE TITLE
Typo in ShapeMaster manual regarding Response control

### ISSUE THREAD

**Issue by pyrodogg** [MarcBoule/MindMeldModular#86]
On page 14 of the PDF manual for ShapeMaster there is a small typo.

The section for the Response control refers to the Warp control.

https://github.com/MarcBoule/MindMeldModular/blob/master/doc/MindMeld-ShapeMaster-Manual-V1_0.pdf

**Comment by Torinbob** [comment]
Ah yes - I'll fix it.

Thanks for letting us know!
