### ISSUE TITLE
Question: Fade CV - Outputs?

### ISSUE THREAD

**Issue by mikeloveridge** [MarcBoule/MindMeldModular#9]
Hi!  Sorry, should have included this with the other question.

I see you have a Fade CV and I thought this would be a Fade CV input, but it seems to be an output. I can see some possibilities for there being a CV out for faders, but I really would like an input just like there is for the Mute and Solo. Maybe you have this and I'm missing it.
Sorry for all the submissions. I'm done, I think. :) Thanks again for making this module!
Mike

**Comment by MarcBoule** [comment]
There are Vol CV inputs for tracks, which can be used to control fades manually from external sources. They correspond to the jacks on the third row from the top labeled "V". If you want to trigger fades from external source, you the Mute CV inputs will actually trigger fades when tracks are in fade mode, so perhaps this is more what you are after. With these two options it should hopefully cover what you would like to do. Cheers!
