### ISSUE TITLE
Channel names on MixMaster

### ISSUE THREAD

**Issue by omricohenmusic** [MarcBoule/MindMeldModular#91]
Hi Marc and Steve!
I hope you're doing well :) Didn't want to disturb you so I'm reporting this here. When I enter a name for a channel on MixMaster (both versions), and then I want to name the next track, when I hit TAB, it jumps to the next track but as soon as I enter one character, it jumps to the end of the name. It's been like this for quite some time but I always forgot to mention this. 

Thanks so much!

**Comment by MarcBoule** [comment]
Hi Omri,

That's weird indeed, we'll take a look. 

btw, thanks also for your comments to me a little while back about the ctrl/cmd clicking menus (so they stay open), and also for also nudging me to do jack and parameter labels (it was a pain, but worth it in the end) ;-)

Doing well over here, hope it's the same for you!

Cheers,

Marc

**Comment by omricohenmusic** [comment]
Hi Marc!

That's great, thanks for taking a look 🙂 I have to do this more. I encounter so many things with different modules and I always forget to report them... Anyway, I'm doing well, thanks 🙂  Cheers!



________________________________

**Comment by MarcBoule** [comment]
This should be fixed now. We've updated the builds in the Releases if ever you want to grab the new version. Thanks again Omri, take care!

https://github.com/MarcBoule/MindMeldModular/releases/tag/v2.1.0b

**Comment by omricohenmusic** [comment]
Thanks so much, Marc!
________________________________
