### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by nexxai** [MarcBoule/MindMeldModular#92]
Hi Marc, I was wondering if there is any possibility of adding a small(?) feature to ShapeMaster (or ShapeMaster Pro) that would allow for a shape to start and end at different levels when the trigger is set to "T/G".

The end goal of a feature like this would be to allow something like an extremely long fade in automation at the beginning of a recording (starting at 0 and increasing to max). Right now, such a shape is not technically possible, as the end would be forced to reset to 0 or you would have to add an extremely quick peak of max before going back to 0 and then sliding up over time.

My notional idea of how something like this would work (and obviously doesn't have to be like this but just as a conversation starter) would be a button that would be enabled per shape that would remove the restriction of not requiring the start and end points to be identical.  The button to "enable the disabling" is so that it wouldn't be a breaking change to any existing setups.

I haven't had a use for the extra features of ShapeMaster Pro so I haven't purchased it, but would obviously be willing to do so if this was made as a Pro-only feature.

Thanks for your consideration, and thank you so much for these insanely useful tools!

**Comment by Petervos2018** [comment]
You could use the sustain function, together with a high gate like this : 

![afbeelding](https://user-images.githubusercontent.com/46076474/172669974-232ee7c1-664c-4e10-9e8e-c8e89368181a.png)

**Comment by nexxai** [comment]
@Petervos2018 Oh damn, this might work perfectly, because now I can have it lock into the loop and then fade out too.  Thank you so much for the idea!

<img width="574" alt="Screen Shot 2022-06-08 at 10 44 48 AM" src="https://user-images.githubusercontent.com/4316564/172671638-0e6a45c5-2512-4ae0-b084-685471557fe9.png">

**Comment by nexxai** [comment]
@Torinbob Well that's even better!  Thank you - I had no idea!

**Comment by Petervos2018** [comment]
I don't think it does what you want, AFAIK it jumps back to 0 even when the gate is high ?

**Comment by ContemporaryInsanity** [comment]
Why not just use Impromptu Tact?

**Comment by Torinbob** [comment]
Yes you're right - it does go back to the initial voltage (whatever the first node is set too). I remember discussing this with Marc during development and asking if there was a way we could hold it at the end (for precisely the fade in use case mentioned in the OP) but this proved more tricky than it sounds - I can't remember exactly why but there was no easy way to make it happen due to the way SM works internally iirc.


We did the decoupling mainly for when SM is used in CV playhead mode or playing shapes in ping pong so it doesn't glitch at the end when used like that.

As Peter pointed out you can use the sustain feature to do it or you could freeze the playhead with the freeze button when it gets to the desired high voltage.

**Comment by nexxai** [comment]
@ContemporaryInsanity I've never seen this module and it looks even better than using ShapeMaster; in fact, this is literally exactly what I've been looking for.  4s/V seems way too fast for what I'm trying to do (fades over 5-10 minutes) but it looks like I can right click on that knob and just adjust the number of seconds to more than 4, despite what the "front plate"(?) suggests.  Thank you for this!

**Comment by ContemporaryInsanity** [comment]
Written by the same genius responsible for ShapeMaster.

Thanks as always for all of your efforts Marc :)

**Comment by nexxai** [comment]
Even with the "Rate Knob x3" option in the right click menu of the module isn't enough.  Dammit.

**Comment by Torinbob** [comment]
Best option with SM is to use decoupling with sustain on at the end and a high gate. SM can deal with lengths up to 30 mins.
<img width="871" alt="Screenshot 2022-06-08 at 18 28 12" src="https://user-images.githubusercontent.com/41232273/172680110-cc9ee3ab-17b4-4ae9-981d-20fbe016b5eb.png">

and it stays high at the end

<img width="871" alt="Screenshot 2022-06-08 at 18 27 31" src="https://user-images.githubusercontent.com/41232273/172680165-e808a136-d04d-4eb9-98e5-b62ad8a9f3b4.png">

**Comment by nexxai** [comment]
Yep, I think that's what I'm going to have to do.  Thanks everyone for the suggestions!
