### ISSUE TITLE
ShapeMaster: Node triggers vs. playback modes

### ISSUE THREAD

**Issue by ZwergNaseXXL** [MarcBoule/MindMeldModular#94]
- Have a channel with only one node at t=0 and its counterpart at t=max.
- Switch VCA output to node triggers.
- In auto, T/G and gate ctrl modes, a trigger signal appears for the end node, but not for the start node. That's odd. I guess I'd prefer one at the start for coupled end nodes and an additional one at the end only for decoupled end nodes. For looping in auto and gate ctrl modes, it's just that the very first trigger is missing.
- In CV playhead mode, there's absolutely no trigger. This is definitely wrong. (I'm using a ramp signal from another channel to drive the CV input.)
- Currently it doesn't matter if you toggle coupled/decoupled end notes in any mode. The behavior stays the same.
- It also doesn't matter if you add additional nodes. Missing end nodes are still missing.
- Workaround: Add one additional node and drag it to the very left. Kinda works, but time can't go lower than 0.00001s, which might be an issue, depending on the use case.

**Comment by Torinbob** [comment]
Hi - thanks for reporting this. I've done a test and there does seem to be an issue with triggers not being generated for the first nodes. And you're right about the last node not generating a trigger either in CV playhead mode when there are only 2 nodes (but if you add other nodes they do generate triggers). We'll look into it and report back. Thanks again, Steve.
