### ISSUE TITLE
MixMaster : Volume modulation behavior on channel 1 only (polyphony)

### ISSUE THREAD

**Issue by DomiKamu** [MarcBoule/MindMeldModular#99]
Hi Steve & Marc,

I'm discovering a strange behavior concerning the MixMaster module, and volume modulation (V input port, per channel).

When I modulate the volume on channel 1 (from an ADSR envelope generator, as example), many channels are affected, and the number matches polyphony channel number, **instead of channel 1 only**.

For example, if you set polyphony to 3 (MIDI to CV module), channels 1, 2 and 3 are affected by incoming modulation (instead of channel 1).

I precise this behavior doesn't occur when you modulate other channels (assuming this behavior as normal).

Plugin version 2.1.1.
VCV Rack v2.2.0 (standalone), Windows 10.

Thanks.

**Comment by Torinbob** [comment]
Hi Dom,

We added this some time ago as a way to modulate the volume of all channels with one polyphonic cable. It only happens with the volume input on Channel 1. So it's normal and expected behaviour.

Cheers,
Steve

**Comment by DomiKamu** [comment]
Hi Steve,

Okay I understand.

Perhaps an option (contextual menu) to enable/disable this feature, will be an idea ?

Cheers,
Dominique.

**Comment by DomiKamu** [comment]
Can be closed.
